### ISSUE TITLE
Possible error in Ch 3

### ISSUE THREAD

**Issue by jamesriby** [head-first-csharp/fifth-edition#2]
Thanks for a great book! One thing I spotted - in Ch 3 it says half-way through that "Go back to your animal matching program and look for this line of code: Random random = new Random(); You created an instance of the Random class, and then you called its Nextmethod."

However in the animal matching program I don't think we did create a new instance of Random; I think Random was called statically instead?

**Comment by andrewstellman** [comment]
Thank you! Yes, you're right—I missed that. The fourth edition used instances of Random, we switched all of the code to use Random.Shared because it avoids some annoying issues. Looks like I forgot to fix this in Chapter 3. I really appreciate you pointing this out, I'll make sure this gets updated for future printings.
