### ISSUE TITLE
Consider adding Avalonia Support for people who use Linix

### ISSUE THREAD

**Issue by theundergroundsorcerer** [head-first-csharp/fifth-edition#7]
Hey, thanks for the excellent book.

I have question - is it possible to use Avalonia in future editions and/or add Avalonia guide (similar to Blazor)? 
There are several reasons.
1. Some people run Linux, and MAUI doesn't run on Linux. This is the main reason. Blazor is not 100% viable alternative to those who can't run MAUI.
2. Avalonia is the most actively developed XAML framework right now, and seems to get a plenty of love both from users and developers (unlike MAUI, sad to admit that). 
3. If not Avalonia - may be project uno could be used instead?

**Comment by andrewstellman** [comment]
I would love to use Avaloina or Uno, and I've even talked to the Unu folks about what it would take. I've been using using Linux since it first came out in the early 90s, so I would love to see this work for our Unix readers. But it's just not something I can make happen any time soon.

The sheer amount of effort required to make that happen is more than I can do by myself—we're probably talking months of my time to get it right—and there is a LOT that goes into getting these right. It's much more than just writing the code for the projects: it's taking the time to come up with explanations that work for everyone, building in bugs that readers can sleuth out, and teaching everything each exercise needs to teach in a way that builds on what we just learned and sets things up for the next chapter.

That's why I made sure that every project in the Blazor guide gives you everything you need to get to reinforce the learning and get prepared for the next ideas.

I'm working really hard to give our readers whatever I can. Honestly, it's Sunday, and I would love to be playing _Star Wars Outlaws_ this morning rather than working on audio for the video for the YouTube channel. But I'm really committed to doing my best to give our readers everything I can to help them learn.

Sorry this isn't the answer you were hoping for.
